apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: nfs-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/data
    server: 192.168.151.206