
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # Aantal replica's
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # De nieuwste NGINX-image
        imagePullPolicy: Always # Forceert Kubernetes om altijd de laatste image op te halen
        ports:
        - containerPort: 80
