apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Elke pod heeft toegang tot zijn eigen volume
  storageClassName: longhorn  # Zorg dat je Longhorn StorageClass is ingesteld
  resources:
    requests:
      storage: 5Gi  # Vraag 5Gi opslag aan per pod
