apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-upgrade-sa-dev
  namespace: nginx-dev
spec:
  schedule: "0 1 * * *"  # Voer de upgrade elke dag om 1:00 uit
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: nginx-upgrade-sa-dev  # Consistente naamgeving
          containers:
            - name: nginx-upgrade-container
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl set image deployment/nginx-deployment nginx=nginx:latest --record -n nginx-dev
          restartPolicy: OnFailure
