apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always # Forceert Kubernetes om altijd de laatste image op te halen
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-storage
  volumeClaimTemplates:
  - metadata:
      name: nginx-storage
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
