apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-upgrade-sa-dev
  namespace: nginx-dev
spec:
#  schedule: "*/3 * * * *"  # Voer elke 3 minuten uit
  schedule: "0 1 * * *"  # Voer de upgrade elke dag om 1:00 uit
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: nginx-upgrade-sa  # Gebruik de aangemaakte ServiceAccount
          containers:
            - name: nginx-upgrade-container
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl set image deployment/nginx-deployment nginx=nginx:latest --record -n nginx
          restartPolicy: OnFailure




