apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Aantal replica's
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always  # Zorgt ervoor dat Kubernetes altijd de nieuwste versie van de image gebruikt
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-storage  # Verwijzing naar het PVC
          mountPath: /usr/share/nginx/html  # Pad waar de NGINX-bestanden worden geplaatst
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc  # Verbindt de PVC met deze volume
