apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-rwx-pvc
  namespace: nfs-system  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client  
  resources:
    requests:
      storage: 1Gi