apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-upgrade-sa-dev
  namespace: nginx-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-upgrade-role-dev
  namespace: nginx-dev
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-upgrade-rolebinding-dev
  namespace: nginx-dev
subjects:
  - kind: ServiceAccount
    name: nginx-upgrade-sa
    namespace: nginx-dev
roleRef:
  kind: Role
  name: nginx-upgrade-role
  apiGroup: rbac.authorization.k8s.io
